#+ summary: Select LSQ queries by a number of parameters
#+ endpoint: http://lsq.aksw.org/sparql
#+ enumerate:
#+    - feature

PREFIX lsqv: <http://lsq.aksw.org/vocab#>
PREFIX sp: <http://spinrdf.org/sp#>
SELECT *  FROM <http://data.semanticweb.org>
 WHERE {
    ?id sp:text ?query ;
        lsqv:resultSize ?rs ;
        lsqv:triplePatterns ?tp ;
        lsqv:runTimeMs ?rt ;
        lsqv:usesFeature ?_feature_iri .
   FILTER (?rs > 10 && ?tp <5  && ?rt < 50 ) }
